[general]
import = ["$HOME/.config/alacritty/themes/themes/nord.toml"]

[window]
dimensions = { columns = 100, lines = 35 }


[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font" }

[terminal]
shell = {program = "zellij", args = ["--shell", "zsh"]}
