import = ["~/.config/alacritty/alacritty-theme/themes/nord.toml",]

[shell]
program = "/usr/local/bin/zellij"

[window]
blur = true
opacity = 0.85
decorations = "Buttonless"

[font]
size = 13
normal = {family = "JetBrainsMono Nerd Font"}

