[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml",]

[font]
size = 15
normal = {family = "JetBrainsMono Nerd Font"}

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 133, lines = 30 }
